---
- name: Clone all Codeberg repos into the exact folders you specified
  hosts: arch_vm
  become: true
  vars:
    codeberg_repos_ls:
      - "ssh://git@codeberg.org/Spoljarevic/Ansible.git"
      - "ssh://git@codeberg.org/Spoljarevic/Bash-Scripts.git"
      - "ssh://git@codeberg.org/Spoljarevic/Support-Website.git"
      - "ssh://git@codeberg.org/Spoljarevic/ssh-config.git"
      - "ssh://git@codeberg.org/Spoljarevic/Dotfiles.git"
      - "ssh://git@codeberg.org/Spoljarevic/FreePBX-17-Container.git"
      - "ssh://git@codeberg.org/Spoljarevic/Blog.git"
      - "ssh://git@codeberg.org/Spoljarevic/Compose.git"
      - "ssh://git@codeberg.org/Spoljarevic/Profile.git"
      - "ssh://git@codeberg.org/Spoljarevic/Family-Automation.git"

    codeberg_repos_w2i:
      - "ssh://git@codeberg.org/Who2Industries/FreePBX-17-Container.git"
      - "ssh://git@codeberg.org/Who2Industries/GitHub-Business-Profile.git"
      - "ssh://git@codeberg.org/Who2Industries/GitLab-Business-Profile.git"
      - "ssh://git@codeberg.org/Who2Industries/coming-soon-website.git"
      - "ssh://git@codeberg.org/Who2Industries/Ansible-Playbooks.git"

    codeberg_repos_w2i_od:
      - "ssh://git@codeberg.org/Who2Industries-Odysee/Ansible-Playbook-Showcase.git"
      - "ssh://git@codeberg.org/Who2Industries-Odysee/Dotfiles.git"

    repo_groups:
      - base_dir: "~/git/ls"
        repos: "{{ codeberg_repos_ls }}"
      - base_dir: "~/git/w2i"
        repos: "{{ codeberg_repos_w2i }}"
      - base_dir: "~/git/w2i/od"
        repos: "{{ codeberg_repos_w2i_od }}"

  tasks:
    - name: Ensure the required parent directories exist
      ansible.builtin.file:
        path: "{{ item.base_dir }}"
        state: directory
        mode: "0755"
      loop: "{{ repo_groups }}"

    - name: Clone each repo into its proper folder
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ item.0.base_dir }}/{{ (repo_url | basename) | regex_replace('\\.git$', '') }}"
        version: "HEAD"
        force: no
        accept_hostkey: yes
      vars:
        repo_url: "{{ item.1 }}"
      loop: "{{ repo_groups | subelements('repos') }}"
      loop_control:
        label: "{{ repo_url }} → {{ item.0.base_dir }}"
