---
- name: Install yay and AUR
  hosts: arch_vm
  become: true
  tasks:
    - name: Install base-devel, git and go
      ansible.builtin.pacman:
        name:
          - base-devel
          - git
          - go
        state: present
        update_cache: yes

    - name: Create the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
      become: yes

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: '0644'
        validate: 'visudo -cf %s'
      become: yes

    - name: Install yay with makepkg
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present
      become: yes
      become_user: aur_builder

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        use: yay
        name:
          - cmatrix-git
          - onlyoffice-bin
          - proton-mail-bin
          - proton-pass-bin
          - tofi
          - vesktop-bin
          - vscodium-bin
          - zen-browser-bin
          - snapd
      become: true
      become_user: aur_builder
