---
- name: Raspberry Pi OS post-install setup
  hosts: all
  become: true

  vars:
    deb_packages:
      - curl
      - fail2ban
      - wget
      - git
      - ansible
      - vim
      - neovim
      - btop
      - rsync
      - lf
      - cockpit
      - cockpit-machines
      - libvirt-daemon-system
      - cockpit-podman
      - podman
      - podman-compose
      - cockpit-storaged
      - cockpit-packagekit
      - network-manager
      - firewalld
      - udisks2
      - pcp
      - sudo
      - doas
      - aardvark-dns

    services:
      - name: fail2ban.service
        state: started
        enabled: true
      - name: cockpit.socket
        state: started
        enabled: true
      - name: firewalld.service
        state: started
        enabled: true

  tasks:
    - name: Ensure the apt cache is up to date
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required Debian packages
      ansible.builtin.apt:
        name: "{{ deb_packages }}"
        state: present
        install_recommends: no

    - name: Ensure selected systemd units are enabled and running
      ansible.builtin.systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
        daemon_reload: true
      loop: "{{ services }}"
      register: svc_result
      failed_when: svc_result.failed
