---
- name: DNF Updater for RHEL-based clients
  hosts: all
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
